provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  piedpiper-pycoverage-function:
    lang: python3-flask
    handler: ./piedpiper-pycoverage-function
    image: piedpiper-pycoverage-function:latest
